services:
  db:
    container_name: 'race-database'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DATABASE_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432'
    networks:
      - race-network
  app:
    container_name: 'race-app'
    build: .
    environment:
      - 'SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}'
      - 'SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DATABASE_NAME}'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - race-network
networks:
  race-network: